spring.application.name=telegram-lead-bot


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

bot.token=${BOT_TOKEN}
bot.admin-chat-id=${ADMIN_CHAT_ID}

app.stats.cron=${STATS_CRON}

logging.level.root=INFO
logging.level.com.example.telegramleadbot=INFO